HAI 1.2
  I HAS A COUNT ITZ 1

  IM IN YR LOOP UPPIN YR COUNT TIL BOTH SAEM COUNT AN 11
    BOTH SAEM 0 AN MOD OF COUNT AN 3, O RLY?
      YA RLY
        VISIBLE "FIZZ"
      MEBBE BOTH SAEM 0 AN MOD OF COUNT AN 5
        VISIBLE "BUZZ"
      NO WAI
        VISIBLE COUNT
    OIC
  IM OUTTA YR LOOP
KTHXBYE
