SO IM LIKE MODDIN WIT X AND Y OK?
  I CAN HAS X SMASHES NICELY INTO Y
  U TAKE X TAKE AWAY Y OF THOSE I

SO IM LIKE FIZZBUZZIN WIT N OK?
  IZ MODDIN WIT N AND FIV OF THOSE THR33 OK KINDA LIKE EASTERBUNNY?
    U TAKE "FizzBuzz"
  OR IZ MODDIN WIT N AND FIV OK KINDA LIKE EASTERBUNNY?
    U TAKE "Buzz"
  OR IZ MODDIN WIT N AND THR33 OK KINDA LIKE EASTERBUNNY?
    U TAKE "Fizz"
  NOPE?
    U TAKE N

GIMME EACH N IN UR NUMBRZ CHEEZBURGER AND 101 OK?
  VISIBLE FIZZBUZZIN WIT N!
